### ISSUE TITLE
API Error with HassOS 9.0.0

### ISSUE THREAD

**Issue by skitzo2000** [hassio-addons/addon-zwave-js-ui#416]
# Problem/Motivation
![Screenshot 2022-09-21 095305](https://user-images.githubusercontent.com/600824/191524474-8d12a47a-72ae-4bdf-bae2-210cf8d80977.png)

## Steps to reproduce
Upgrade HA to Version 9.0.0 with ZwaveJS2MQTT Addon configured and enabled

## Proposed changes
Upgrade Underlying API version(maybe included in your latest commit, but not yet pushed into the HA repo yet??)

**Comment by frenck** [comment]
> Upgrade HA to Version 9.0.0 

That version does not exist. So not sure what you are looking for.

> Upgrade Underlying API 

That already is the latest and greatest.

**Comment by skitzo2000** [comment]
Sorry I shold have clarified this is on Hass.io

Home Assistant 2022.9.5
Supervisor 2022.09.1
Operating System 9.0
Frontend 20220907.2 - latest

**Comment by TheDK** [comment]
That error usually means you have to update Z Wave JS 2 MQTT to one of the recent versions…

**Comment by skitzo2000** [comment]
I'm on the latest 0.47 JS2MQTT
![Screenshot 2022-09-21 154419](https://user-images.githubusercontent.com/600824/191596315-f0faa7b2-311a-4472-860c-9eced46c82f3.png)

**Comment by TheDK** [comment]
That does work with HA 2022.09 - but maybe update to todays v1.0.0 and see what happens?

**Comment by skitzo2000** [comment]
@TheDK That doesn't seem to be upstreamed into hassOS yet.  I'm on the latest available Core version for HassOS ATM

**Comment by TheDK** [comment]
I meant the most recent version of this add-on, which as of today is 1.0.0
