### ISSUE TITLE
Widom zwave device not recognized

### ISSUE THREAD

**Issue by El-mou33** [hassio-addons/addon-zwave-js-ui#421]
# Problem/Motivation
> (Why the issue was filed):  Widom zwave plug devices aren't recognized by home assistant and home assistant used to be recognize. I actually don't know why, but months ago worked well but now it isn't.

## Expected behavior: when putting the device into inclusion mode and home assistant through zwavejs2mqtt addon in inclusion mode too, should be paired.

> (What you expected to happen): when putting the device into inclusion mode and home assistant through zwavejs2mqtt addon in inclusion mode too, should be paired.

## Actual behavior

> (What actually happened): Home asisstant and widom plug doesn't recognize each other. Theinclusion time expires without any changes, no errors but never gets included

## Steps to reproduce

> (How can someone else make/see it happen): Click on the addon into actions, manage nodes, inclusion mode. Put at the same time the device into inclusion mode. The addon and the plug never recognize each other, and the inclusion time expires without any changes. The logs doesn't show any relevant. 
This are my 7 aeotec stick controller settings: Normal power level: 9.9 dBm, Measured output power at 0 dBm: 0 dBm, Region: Europe.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Unfortunately, this is not something the add-on can help you with. Add-ons wrap existing software, in this case the Z-Wave JS UI. 

The add-on does not implement or provide device-specific implementations, we simply ship what is provided from upstream.

Please report your issue with the upstream Z-Wave JS project (as linked in the add-on documentation).

Sorry!

../Frenck
