### ISSUE TITLE
Topology broken after reboot

### ISSUE THREAD

**Issue by oeiber** [hassio-addons/addon-zwave-js-ui#422]
After upgrading to 1.0.0, my zwave topology gets broken on every reboot. One or more devices are shown as dead and the network is extremly slow. There are also no connections showing up in the topology view. After restoring a nvme backup to my uzb1 controller the network works normaly untul next reboot.  I‘m using the latest home assistant version (supervised) as well as the latest zwave js ui version. In addition I‘m using the latest firmware provided for my controller.

**Comment by bpbradley** [comment]
I can confirm the same behavior with respect to the topology view after upgrading to 1.0.0. I am not showing dead nodes or a slow network though.

**Comment by twinkie0101** [comment]
The update today (1.0.1) fixed this for me.
