### ISSUE TITLE
About section typo?

### ISSUE THREAD

**Issue by amsmith525** [hassio-addons/addon-zwave-js-ui#430]
In README.md it says "provides a decouled gateway" -- I'm assuming this was supposed to say decoupled?

**Comment by sinclairpaul** [comment]
You can issue a PR by clicking the below when browsing the file: 
![image](https://user-images.githubusercontent.com/24625998/196007306-ab4958b9-042a-4415-beac-ce9340356680.png)

**Comment by TheDK** [comment]
I already have:
https://github.com/hassio-addons/addon-zwave-js-ui/pull/420
