### ISSUE TITLE
All controls (switches, shutters, etc) stop working after a while

### ISSUE THREAD

**Issue by Heelderpeel** [hassio-addons/addon-zwave-js-ui#434]
all my zwave controls stop working after a while (after a reboot). 

The zwave network itself seems to be working, as I still get regular data packets from the energy monitor meter. Nonetheless, any switch (for lights, for example) does not do anything.

I have to reboot in order to get full control of my house again, but that does not last for long (not sure how long does it take until the controls are unresponsive).

I know it is a long shot from this description, but is anyone experiencing the same problem? Any clues of what could be causing this?

FYI: I’m first using the zwave JS addon now i swiched to zwave JS UI Current version: 1.1.0
The problem is the same.
Home Assistant 2022.10.5
Supervisor 2022.10.0
Operating System 9.2
Frontend-versie: 20221010.0 - latest

I saw that there have been people with the same problem before, that's why I report it like this.
My English isn't great, so I hope it's clear.
If there's anything I can do I'd like to hear about it.

**Comment by Heelderpeel** [comment]
It looks like Zwave JS UI 1.2.0 fixed the probleem. 
I monitor it a couple off days and wil close the issue

**Comment by Heelderpeel** [comment]
Unfortunately after 3 days the problem is back.

**Comment by jeffromgbg** [comment]
Im experiencing the same problem. I can see in zwavejs event log that controller receives data from zwave devices but Home Assistant mark the device as unavailable.

**Comment by nameetpai** [comment]
Exact same problem here. I'm on 1.3.0.

**Comment by nicoxygen** [comment]
same problem with 1.3.0, any solution ?

**Comment by Heelderpeel** [comment]
👍

**Comment by Yobby** [comment]
I'm having the same with version 1.4.2. after running for about a week.
The Web UI says it's not running, and in de addon-section of Home Assistant, Z-Wave JS UI is marked as not running, with only Start and Uninstall as available options, but the logs continue to fill with node updates. Pressing Start doesn't do anything, neither does restarting Home Assistant. Only a reboot of the RPi helps, as I don't know to restart this addon outside of HA.

Running on a Raspberry Pi 3 with
 Home Assistant 2023.1.4 
Supervisor 2022.12.1 
Operating System 9.4 
Frontend 20230110.0 - latest

**Comment by michalpulda** [comment]
I have the same problem.

Running on a Raspberry Pi 4
Lastest version of everything

**Comment by michalpulda** [comment]
Update on the issue: I have restarted and rebooted everything many times, which didn't help. In the end out of frustration I unplugged the z-wave dongle (Z-Wave.Me) and connected it again while the system was running and it seemed to have helped. Working flawlessly for 4 days now. Hope it will last.

**Comment by ffcruz85** [comment]
@michalpulda did that solution keep working for you? I did a full power down and that got me back up and running, but now it happened again a week later

**Comment by Heelderpeel** [comment]
for me the problem was a broken Neo coolcam wall plug (and maybe the controller.) I replaced them both and it has been running for a while now without any problems.
all I can say is check your devices, I couldn't find it in the log, all devices seemed to be sending normal traffic.
the big question is now where do you start.........
If you use NEO coolcam then I would start there (1 by 1)

**Comment by michalpulda** [comment]
> @michalpulda did that solution keep working for you? I did a full power down and that got me back up and running, but now it happened again a week later

Yes, it works from that time just fine. However, I have only 5 z-wave devices, so my network is tiny (compared to 70+ zigbee devices).
