### ISSUE TITLE
Logging not respecting LogLevel attribute

### ISSUE THREAD

**Issue by Spartan-II-117** [hassio-addons/addon-zwave-js-ui#435]
# Problem/Motivation

>Z-Wave JS UI logs are filling up my drive!

## Expected behavior

>Z-Wave JS UI should respect log level settings and should only write to one system log (if any)

## Actual behavior

> Z-Wave JS UI Addon writes to three separate system level logs (messages, syslog, & user.log and in great verbosity, addon is set to log level: Error

## Steps to reproduce

> May only affect supervised installation type, but aside from that all i had to do was run the current or previous version. I do not know at what point this started happening, but i arrived home from work yesterday to a non-functional system due to the system having 0 bytes available on /

## Proposed changes

> Limit log writing to a single system level log file, and set the default log level to warning or error.
> alternately keep logging entirely within the addon configuration and do not write to system level logs at all.

**Comment by frenck** [comment]
> addon is set to log level: Error

Add-on log level is related to add-on internal, not the software running inside of it
