### ISSUE TITLE
Issue of Z-Wave JS 

### ISSUE THREAD

**Issue by DEC888** [hassio-addons/addon-zwave-js-ui#443]
Hi,

The Z-Wave JS app always comes up with a "searching for device" status (see attached screenshot), which prevents me from adding and removing devices, I tried clicking the STOP searching button, but it doesn't work, any suggestions?

![Issue of Z-Wave JS](https://user-images.githubusercontent.com/56387118/201815472-d74c48c0-8fff-4197-a6fd-2fed2221aa8d.jpg)

Thanks.
-
Best Regards,
David

**Comment by frenck** [comment]
Hi there @DEC888 👋 

I think you are mixing up two things. This is the issue tracker and repository of the Z-Wave JS UI add-on, but your report and screenshot are about Home Assistant. There is nothing I can do with this issue. Please report your issue with the Home Assistant project.

../Frenck

**Comment by DEC888** [comment]
Hi @frenck , 
Thanks for your quick reply. 
Do you happen to know how do we disable the annoying "searching" behavior ? I submitted a ticket to Home Assistant project, but still have not received a response.

-
Best Regards,
David
