### ISSUE TITLE
Minoston MP21Z Fails after Z-Wave JS 1.3.0 Update

### ISSUE THREAD

**Issue by jdggit** [hassio-addons/addon-zwave-js-ui#445]
# Problem/Motivation

Minoston MP21Z Wall Plug has been working for years until latest update, then node was dead. Rolled back to 1.2.1 and wall plug was working again. No other changes.

## Expected behavior

Expected seamless update...

## Actual behavior

With 1.3.0 Update tried rebooting, reloading, healing, re-interviewing, pinging, etc. Node was declared dead. All other zwave devices are working including locks, wall plugs, wall switches, etc. No intervention needed, everything came alive on it's own. 

## Steps to reproduce

Rolled back to 1.2.1 after the problem was noted. After which I did have to send a ping to the node to get it to come alive. All is fine. Updated again, same problem again. 

## Proposed changes

I can provide logs or other data as needed with either code version running. Using HA UI exclusively. Specify what files or logs are needed and where I can get them or what I need to do to generate them.

**Comment by frenck** [comment]
Hi there @jdggit 👋 

From an add-on perspective, there is not much I can do about this. This is about device management/support from Z-Wave JS UI itself and not the add-on.

Add-ons wrap existing software, in this case Z-Wave JS UI. If they have an issue, the add-on will have an issue too. If they fix it, the add-on won't have the problem either.

Please report your issue with the Z-Wave JS project.

Sorry! Wish I had a better answer for you 🙏 

../Frenck
