### ISSUE TITLE
Z-Wave JS UI out of date

### ISSUE THREAD

**Issue by tamorgen** [hassio-addons/addon-zwave-js-ui#447]
There are device definitions updated in Z-Wave JS UI 8.5.0 that I'm unable to access.  

> (Why the issue was filed)

HACS add-on needs to update Z-Wave-JS 10.3.1, Z-Wave-JS-UI 8.5.1

## Actual behavior

Stuck at 10.3.0, 8.4.1

**Comment by frenck** [comment]
> HACS add-on needs to update 

HACS doesn't provide add-ons.

> There are device definitions updated in Z-Wave JS UI 8.5.0 that I'm unable to access.

Update of device databases are not related to add-on UI updates.

Closing this issue as it is an request, not an issue.

../Frenck
