### ISSUE TITLE
Integration can't connect to Add-on after upgrade 1.6.0 to 1.6.2

### ISSUE THREAD

**Issue by Masterz69** [hassio-addons/addon-zwave-js-ui#464]
# Problem/Motivation

ZWave JS upgraded from 1.6.0 to 1.6.2.
Add-on itselves looks working fine - devices send data, UI working.

But integration fails to connect to Add-on.

## Expected behavior

> (What you expected to happen)

## Actual behavior

```
2023-02-12 11:37:31.928 INFO Z-WAVE-SERVER: ZwaveJS server listening on 0.0.0.0:3000
2023-02-12 11:37:33.072 INFO Z-WAVE-SERVER: DNS Service Discovery enabled
s6-rc: info: service discovery successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started

Retrying setup: Failed to connect: Cannot connect to host a0d7b954-zwavejs2mqtt:3000 ssl:default [Connect call failed ('172.30.33.6', 3000)]

Logger: homeassistant.config_entries
Source: config_entries.py:1133
First occurred: 11:36:35 (2 occurrences)
Last logged: 11:41:36

Config entry 'Z-Wave JS' for zwave_js integration not ready yet: 
Failed to connect: Cannot connect to host a0d7b954-zwavejs2mqtt:3000 ssl:default 
[Connect call failed ('172.30.33.6', 3000)]; Retrying in background

2023-02-12 11:44:52.923 INFO Z-WAVE-SERVER: ZwaveJS server listening on 0.0.0.0:3000
2023-02-12 11:44:54.078 INFO Z-WAVE-SERVER: DNS Service Discovery enabled
```
Add-on restart change nothing - integration show same error: Cannot connect...

Integration->Add-on connection restored as soon rollback 1.6.0 is completed.

Diagnostic dump attached: 
[config_entry-zwave_js-ad3bae36f23c64c0f09a1044fcb47c4b.json.txt](https://github.com/hassio-addons/addon-zwave-js-ui/files/10715776/config_entry-zwave_js-ad3bae36f23c64c0f09a1044fcb47c4b.json.txt)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by ffcruz85** [comment]
I am experiencing something similar after the update as well, but iny case the add-on is not starting. However, when I look at the add-on logs, it shows information being transmitted by the z-wave network. Following a tip from a forum, I powered down the host and removed the power from my raspberry pi before restarting. That fixed it for a week. It just happened again now

**Comment by Masterz69** [comment]
Just installed 1.6.3 (over 1.6.0) - integration connected to Add-on after "Reload".
Seems issue fixed.
