### ISSUE TITLE
Support for /dev/serial/by-id devices

### ISSUE THREAD

**Issue by briped** [hassio-addons/addon-zwave-js-ui#466]
# Problem/Motivation
> (Why the issue was filed)

Serial port changed after reboot

## Expected behavior
> (What you expected to happen)

I guess I expected the port to not change, or in lieu of that, that it was possible to select the unchanging path using by-id. Adding the "/dev/serial/by-id/usb-0658_0200-if00" path manually did not work.

## Actual behavior
> (What actually happened)

Serial port changed after reboot and I could not configure it using by-id path.

## Steps to reproduce
> (How can someone else make/see it happen)

Try to configure serial port using the by-id path.

## Proposed changes
> (If you have a proposed change, workaround or fix, describe the rationale behind it)

If possible, allow the use of by-id paths, so changing ttyUSB#/ACM# does not break z-wave functionality

**Comment by frenck** [comment]
It already allows using device by their ID paths.

**Comment by briped** [comment]
Hmm. I swear I tried with `/dev/serial/by-id/usb-0658_0200-if00` and it not working, before I so I ended up using `/dev/ttyACM0`. However, just tried again with `/dev/serial/by-id/usb-0658_0200-if00` and this time it worked. Maybe I just weren't patient enough for the connection to be established. Anyway, thank you for responding.
