### ISSUE TITLE
Unable to pull the file using docker

### ISSUE THREAD

**Issue by hassan-xy** [hassio-addons/addon-zwave-js-ui#469]
Unable to install zwave-js-ui on my aarch64 platform board.  

 I am trying to use zwave-js-ui for my aarch64 board, but the issue is that its too complex and difficult to install docker in my board. I have searched everywhere to find an easier method but to no avail. My board does not have the necessary packages to install docker and seems to be incompatible with it. 

If there is any other way to install zwave-js-ui for the aarch64 platform board, please let me know. Also please share the steps you have taken to install docker in your aarch64 board. I have my board configuration below.
Operating System: Ubuntu 18.04.6 LTS
Kernel: Linux 3.10.65
Architecture: arm64
Using the command <uname -m> prints **aarch64** on the console
## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This is not a general Docker container, but an Home Assistant add-on. You can't use add-ons in regular container installation methods.

../Frenck

**Comment by hassan-xy** [comment]
Hi Frenck,
Thanks for you reply.
I would like to know if there is still another method to download zwave-js-ui/aarch64 without using the pull feature from docker. I know it's an add-on but I still think I might be able to run the application in my hardware board and use it to control some of my zwave devices.
