### ISSUE TITLE
Can I get the aarch64 based file.

### ISSUE THREAD

**Issue by hassan-xy** [hassio-addons/addon-zwave-js-ui#471]
Can I get the aarch64 based file, since the available packages are not compatible with my board.
If not possible, then is it possible for you to provide the steps on how to download that file.

**Comment by frenck** [comment]
> Can I get the aarch64 based file

? I'm not following this one, it is an add-on. Which file?

**Comment by hassan-xy** [comment]
Hi Frenck,
Thanks for replying.
I have tried running the zwave-js-ui-linux on my laptop vs code and it perfectly. I would like to run the same on my board which is an aarch64 and I am currently facing incompatibility issues. Can you send the aarch64 based file.

**Comment by frenck** [comment]
Again: Which file? There is no such thing, this is an add-on...

../Frenck

**Comment by hassan-xy** [comment]
The zip file zwave-js-ui-8.8.5.zip has an an arm64, armvhf, armv7, linux and a windows based application. I need an application that is compatible with aarch64 board.
Thanks

**Comment by frenck** [comment]
I think you are mixing up things, this repo/project does not have zip-files.

**Comment by hassan-xy** [comment]
Hi Frenck,
Thanks for replying.
I understand this an add-on and I asking for this at the wrong place.
I apologize for this, I am still a rookie.

I am referring the below page

https://zwave-js.github.io/zwave-js-ui/#/getting-started/other-methods 

and have followed the below steps to get zwave-js-ui

cd ~
mkdir zwave-js-ui
cd zwave-js-ui
# download latest version
curl -s https://api.github.com/repos/zwave-js/zwave-js-ui/releases/latest  \
| grep "browser_download_url.*zip" \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -i -
unzip zwave-js-ui-v*.zip
./zwave-js-ui

I want to run this application in my board that works on aarch64, so I posted this issue here seeing the title zwave-js-ui/aarch64. I get it its an add-on but can you guide me on what I should do.

Thanks and Regards,
Hassan

**Comment by frenck** [comment]
> I understand this an add-on and I asking for this at the wrong place.
> I apologize for this, I am still a rookie.

Don't worry.

> I am referring the below page

> [zwave-js.github.io/zwave-js-ui/#/getting-started/other-methods](https://zwave-js.github.io/zwave-js-ui/#/getting-started/other-methods)

That is not related to this project. You are indeed in the wrong place. This is an add-on, which is installed via the Home Assistant user interface.

For more information see the README in this repository.

Closing this issue, as it is not related to anything here.

../Frenck

**Comment by hassan-xy** [comment]
> > I understand this an add-on and I asking for this at the wrong place.
> > I apologize for this, I am still a rookie.
> 
> Don't worry.
> 
> > I am referring the below page
> 
> > [zwave-js.github.io/zwave-js-ui/#/getting-started/other-methods](https://zwave-js.github.io/zwave-js-ui/#/getting-started/other-methods)
> 
> That is not related to this project. You are indeed in the wrong place. This is an add-on, which is installed via the Home Assistant user interface.
> 
> For more information see the README in this repository.
> 
> Closing this issue, as it is not related to anything here.
> 
> ../Frenck

**Comment by hassan-xy** [comment]
Thanks Frenck
