### ISSUE TITLE
Update will not start service

### ISSUE THREAD

**Issue by silverf1re** [hassio-addons/addon-zwave-js-ui#477]
# Problem/Motivation

> JS UI will not start after upgrade. 

## Expected behavior

> Start

## Actual behavior

> Doesn’t start

## Steps to reproduce

> Home assistant on rpi4 version 10.3.1. Update JSUI to 1.7.1

## Proposed changes

please indicate what more logs/info you need

**Comment by silverf1re** [comment]
Restoring back to 1.6.3 fixed my issue. Looks like there is a breaking change with 1.7.1

**Comment by frenck** [comment]
Please share some logs of the add-on, and the output of `ha info` should be helpful too.

**Comment by silverf1re** [comment]
I just upgraded again to get you that info but now it works. Sorry to waste your time.
