### ISSUE TITLE
Can’t start stopping working 6 hours ago. Image ghcr.io/hassio-addons/zwave-js-ui/armv7:1.7.1 does not exist for addon_a0d7b954_zwavejs2mqtt

### ISSUE THREAD

**Issue by alexbromberek2020** [hassio-addons/addon-zwave-js-ui#478]
Image ghcr.io/hassio-addons/zwave-js-ui/armv7:1.7.1 does not exist for addon_a0d7b954_zwavejs2mqtt
![3ACDBEE8-77B3-482E-878C-98E100C0C993](https://user-images.githubusercontent.com/89488778/223298936-0e5bacb9-ae2d-42bc-beb6-389244ff7143.png)
![BBD3967E-86E4-4C4F-A2AB-3A8D5F5CAA26](https://user-images.githubusercontent.com/89488778/223298946-19571351-03d0-4105-9f84-9856da26ef2d.png)

Can't start break 6 hours ago

**Comment by doug62** [comment]
+1 - Same problem, occurred after I bumped HA version to:

Home Assistant 2023.3.1
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230302.0 - latest

** Also - after that update zwave didn't come back, needed to power off PI, then it came back but some device names were lost/reset to defaults.

**Comment by nameetpai** [comment]
+1

Add-on can't start after latest update.

Failed to start add-on

Image ghcr.io/hassio-addons/zwave-js-ui/aarch64:1.7.1 does not exist for addon_a0d7b954_zwavejs2mqtt

**Comment by jvillanti** [comment]
+1

**Comment by nameetpai** [comment]
For anyone with a broken smart home heavily reliant on zwave devices, if you're stuck with this issue and you have a backup from an older working version, you should be able to get up and running again if you partially restore just this add-on from that pre-upgrade backup. It will effectively downgrade the add-on by pulling the older container.

If you don't have an old pre-upgrade backup, you can apparently just modify your latest backup archive and switch the version in snapshot.json file for the add-on before restoring to force a downgrade. I didn't have to do this myself because I had a backup I could use, but here's a thread that could help - https://community.home-assistant.io/t/how-to-downgrade-addons/331223/17

**Comment by TheDK** [comment]
I just installed it today on my test system, went fine, and given the relative quiet here after several days I’d say it’s safe to assume not everyone is affected by this. Have you tried completely removing the add-on and then re-adding from a backup?

**Comment by doug62** [comment]
@nameetpai @TheDK This problem still persists, I'm hoping we aren't thinking this is resolved, or that downgrading is the solution?  BTW - If i wanted to downgrade this by changing the image tag for this, where I would I find that in the file system?

**Comment by doug62** [comment]
Ping

**Comment by doug62** [comment]
@gazpachoking may I ask how you rolled back? I'm on PI OS/Supervisor.

**Comment by gazpachoking** [comment]
I had a full backup, where I chose to do a partial restore of zwave js ui.

**Comment by TheDK** [comment]
Just updated on an RasPi 3b as well as on an Odroid N2, no problem...

**Comment by doug62** [comment]
Solved - Obviously this was a docker error and not specific to this add on, It could have been resolved with a docker pull, or restoring an older version as some have said but I was able to simply resolve this by doing a partial restore of the 1.7.1/current/corrupt install in place without mods - the restore of the same version triggered HA/Supervisor to do the docker pull... Thanks for the tips tho.

**Comment by doug62** [comment]
ARG: After restoring to an older version, restoring everything worked, but then I updated z-wave js, it worked for abit then started reporting: Retrying setup: Failed to connect: Cannot connect to host core-zwave-js:3000 ssl:default [Connect call failed ('172.30.33.4', 3000)]

**Comment by frenck** [comment]
It does exist, feel free to check:

<https://ghcr.io/hassio-addons/zwave-js-ui/armv7:1.7.1>

If you run into such issues, you might have other problems. Please run `ha supervisor repair` in that case.

Closing this issue, as it is outside of the control of this add-on.

../Frenck
