### ISSUE TITLE
Unable to reach interface from exposed port on configuration page

### ISSUE THREAD

**Issue by N1029676** [hassio-addons/addon-zwave-js-ui#484]
# Problem/Motivation

> I've configured the exposed port to be 3000 and have restarted the add-on but am unable to access the interface on the exposed port despite restarting the add-on and the whole host.

## Expected behavior

> ZWave JS UI would be reachable at `http://ip.of.home.assistant:3000`

## Actual behavior

> Access attempt times out.

## Steps to reproduce

> Configure an exposed port, restart, and attempt to access.

## Proposed changes

> No proposal.

**Comment by matejzero** [comment]
I was hit by this also, I think.

I would like to expose zwave-js-ui websocket on external interface, because my main HA is running on another server. It is possible to do that with that addon?

**Comment by matejzero** [comment]
I set the port to 3000 in addon configuration, restarted the addon and WS is not available on <ip.of.ha>:3000.

**Comment by matejzero** [comment]
I set port to 3000, saved and restarted the service. On the master HA, I set my server URL to ws://ip-of-zwaveJS:3000 and it started to work.
