### ISSUE TITLE
Last update strange entities appeared???

### ISSUE THREAD

**Issue by cfrudolphy** [hassio-addons/addon-zwave-js-ui#492]
# Problem/Motivation
With the last Zwave2MQTT update one of my Jasco light switches had (2) entities added to its configuration.  Entity 1 was a humidifier and entity 2 was a dehumidifier.  I have one other identical Jasco switch and this did not happen to it.  See the screen shots attached.  I am currently running:

> zwave-js-ui: 8.11.0
> zwave-js: 10.12.0
> home id: 4172182925
> home hex: 0xf8ae758d

It was after this update these (2) entities appeared.  When they first appeared after the update they were active I could set a value to them.  After the update to Core 2023.3.6 they were "not longer provided by the add-on" and I was able to delete them.  But as you can see they are still showing in the Zwave2MQTT dashboard.

![Screenshot_2023-03-24_15-03-42](https://user-images.githubusercontent.com/57832151/227630267-4f2db416-e4ba-4e9e-990a-e05a4478826e.png)
![Screenshot_2023-03-24_15-04-25](https://user-images.githubusercontent.com/57832151/227630268-34696e85-eaa3-4e30-86a4-c83f7609145b.png)
![Screenshot_2023-03-24_15-05-01](https://user-images.githubusercontent.com/57832151/227630270-c6c05bb1-8185-40ab-9583-838315568b2e.png)
![Screenshot_2023-03-24_15-08-24](https://user-images.githubusercontent.com/57832151/227630272-1e252eb1-c0e0-4f82-96d6-30144f02713a.png)

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Add-ons wrap existing software, in this case, Z-Wave JS UI. The add-on itself doesn't create entities. If there is an issue with the software an add-on warps, please report it upstream with the project being wrapped.

../Frenck
