### ISSUE TITLE
Cannot connect to ZWave-JS UI via MQTT from external Listener ? 

### ISSUE THREAD

**Issue by RicardP** [hassio-addons/addon-zwave-js-ui#494]
If I understand it right MQTT 2.0 and later needs the "allow_anonymous true" in mosquitto.conf file in order to access MQTT from external IP address!? 
If so I don't see any decent way (for me) to do it as I cannot find even the mosquitto installations within HA, or did I miss any available setting?

Thanks a lot!

**Comment by frenck** [comment]
> If I understand it right MQTT 2.0 and later needs the "allow_anonymous true" in mosquitto.conf file in order to access MQTT from external IP address!?

This is not related to this add-on. Closing.

**Comment by RicardP** [comment]
Why, isn't MQTT broker built into this add-on?

**Comment by frenck** [comment]
Because it isn't needed? 🤷 
It also doesn't come with Spotify.

**Comment by RicardP** [comment]
Funny, but I meant MQTT IS included, generally for internal use, I need also to share ZWave devices for my Domoticz system on external server, but only issue seems MQTT does not allow external connection.

**Comment by RicardP** [comment]
Thanks a lot for your kind attitude !

**Comment by frenck** [comment]
> Funny

I wasn't funny; it isn't related. You are mixing up clients vs. servers. This is not an MQTT server. However, Z-Wave JS UI can connect (as a client) to an MQTT server of your choice.

MQTT is thus not included. Your browser doesn't come with all websites pre-installed either...

>  I need also to share ZWave devices for my Domoticz system on external server, but only issue seems MQTT does not allow external connection.

Again, not related to this add-on, so it cannot be an issue of this add-on. Yet, you report a bug for Z-Wave JS UI.

> Thanks a lot for your kind attitude !

🤷

**Comment by RicardP** [comment]
Ok sorry, thanks for taking the time to explain!
