### ISSUE TITLE
All Z-Wave devices becomes unavailable/unresponsive

### ISSUE THREAD

**Issue by stefanes** [hassio-addons/addon-zwave-js-ui#514]
# Problem/Motivation

I am experiencing [this issue](https://github.com/home-assistant/core/issues/92521), or something similar (or maybe two different issues), but not sure if this is an issue with the Z-Wave JS integration or this add-on. The issue seems to have started happening after updating Z-Wave JS UI to the latest version.

For me the issue seems to appear every few days, and it manifests itself in two different ways:
1. Sometimes all devices turns up dead as described above
2. Sometimes devices just "get stuck" either on or off

When 1) happens, attempting to turn the device on/off generates an API call error. When 2) happens, if turning a device on/off absolutely nothing happens. So far I have not found anything in any logs.

In both instances the issue seems to go away by restarting the Z-Wave JS UI add-on. I unfortunately have no good backup with a previous version of the add-on since I made quite a few changes at the same time as I updated the Z-Wave JS UI add-on. If there is any other way of downgrading (temporarily for test) I would be more than happy do that?

---

| Component | Version |
| --- | --- |
| Home Assistant | 2023.5.2 |
| Supervisor | 2023.04.1 |
| Operating System | 10.1 |
| Frontend | 20230503.3 - latest |
| Z-Wave JS Driver | 10.17.1 |
| Z-Wave JS Server | 1.28.0 |
| Z-Wave JS UI add-on | 1.12.0 |
| Aeotec Z-Stick 7 | 7.19.2 |
| RF Region | EU |

## Expected behavior

Z-Wave devices remain available/responsive.

## Actual behavior

Z-Wave devices becomes unavailable/unresponsive.

## Steps to reproduce

Unclear, so far the issues seems to be very random happening with hours or sometimes days in between.

**Comment by bseal84** [comment]
I too had all my devices go unavailable after upgrading (from 1.11.2) to the Z-Wave JS UI to the latest version (1.13.0). I was still able to pull up the zwavejs2mqtt/dashboard as see all my devices were still connected and could control them from zwavejs2mqtt/dashboard, but I could not get them to change from "unavailable" anywhere in HA. 

Luckily I had a backup that was on 20 hours old so I just restored to 1.11.2.

**Comment by ArsineMan** [comment]
I am having the same issue as bseal84. All devices are unavailable in HA but no problems from the zwave dashboard.

**Comment by stefanes** [comment]
Good point, yes my Z-Wave JS UI dashboard remains responsive. It just start failing sending commands such as binary on/off.

**Comment by hughc-hub** [comment]
Same problem here.. After 1.12 update all my zWave devices change to unavailable. I had to restore from backup to recover my system. 
Is anything we can do to fix it?

**Comment by blahh2** [comment]
Same problem here, all description and location information gone too. Devices work fine if managed outside of UI.

**Comment by ArsineMan** [comment]
just a note on this, I rolled back my 1.13 update and everything is back to normal.

**Comment by bencollinz** [comment]
Same problem. I had to roll back to 1.11.2 back up.

**Comment by rrozema** [comment]
I too had several devices go unresponsive after installing z-wave JS updates. I install pretty much every new (production) version soon after it comes available, so my upgrade path contains all major and minor updates. Currently installed:
zwave-js-ui: 8.16.1
zwave-js: 10.20.0
I did not restore a backup to fix the issues. I saw that for some of the malfunctioning nodes the available options in z-wave JS control panel were not as they used to be: some had only very little of the categories under 'Values' available, less than I was used to see for those nodes. So I re-interviewed those malfunctioning nodes and this fixed the problem for me. I did have to re-interview some more than once before all categories were back again. For others I only refreshed the values and then re-set some of the configuration settings on the nodes. It seems to me that some of the meta data stored about the nodes got corrupted.
Also I see that some nodes do get attributes added that are not even supported by the device. For example, for some nodes I see kwh meter values added, where the device does not have any metering. I even saw such a kWh meter added on a battery operated temp + hum device a few times. Something must be going wrong in either communication or decoding or addressing the messages, resulting in incorrect command classes being added to devices that don't support those classes. Again here, when I re-interview the node, the errors are corrected.

**Comment by bencollinz** [comment]
the update that was just released fixed it for me.

**Comment by mrrobotnic** [comment]
Same thing here.  I just updated to 1.13.1 running Home Assistant OS 2023.4.6.  As soon as the update was completed, the Z-Wave JS interface was available, but Home Assistant said that all devices were offline.  I rolled back to 1.12.0 and restarted and everything came back right away.

**Comment by blahh2** [comment]
Can you explain how to roll back?

**Comment by ydogandjiev** [comment]
@blahh2, go to Settings > System > Backup and select your most recent backup that includes the Z-Wave JS UI Add-on. Select it from the list and tap "Restore":
![image](https://github.com/hassio-addons/addon-zwave-js-ui/assets/3357245/95e33290-4b57-4019-9026-73b42376b1c2)

**Comment by blahh2** [comment]
> @blahh2, go to Settings > System > Backup and select your most recent backup that includes the Z-Wave JS UI Add-on. Pick the add-on from the list and tap "Restore": 

Thanks a lot, I managed to roll back and all OK again :).

**Comment by frenck** [comment]
This issue is in the wrong issue tracker, closing the issue on this end; please report this issue with the Z-Wave JS project. 

../Frenck

**Comment by ydogandjiev** [comment]
Hey @frenck, the Z-Wave JS UI experience shows all the devices and they work just fine there. This problem appears to only impact the way that the apps are being pulled into Home Assitant itself. Are you sure that the Z-Wave JS project is the right place to report what appears to be Home Assistant specific issue?

**Comment by sinclairpaul** [comment]
> Hey @frenck, the Z-Wave JS UI experience shows all the devices and they work just fine there. This problem appears to only impact the way that the apps are being pulled into Home Assitant itself. Are you sure that the Z-Wave JS project is the right place to report what appears to be Home Assistant specific issue?

Then isn't it an issue with the HA integration?
