### ISSUE TITLE
GE 45606 / ZW3001 in-wall paddle dimmer doesn't report correct state

### ISSUE THREAD

**Issue by mhendu** [hassio-addons/addon-zwave-js-ui#515]
# Problem/Motivation

While this worked correctly with my old Vera hub, with Z-Wave JS UI the GE 45606 dimmer switch often does not show the correct device state.

## Expected behavior

If the light is turned on, it should show as on in the UI.

## Actual behavior

The light is turned on but shows as off in the UI.

## Steps to reproduce

If the light is on, restart Home Assistant and it will invariably show as being turned off.

## Proposed changes

Correctly detect the device state and display it properly.

**Comment by frenck** [comment]
Hi there 👋 

Add-ons wrap existing software in a way they are easy to use and install with a Home Assistant instance. In this case, it wraps Z-Wave JS UI. The issue you are reporting is with the upstream software packaged, not the add-on itself.

Please report this issue upstream with the Z-Wave JS project. Once they address the issue and release a fix for it, the add-on will be updated.

Thanks 👍 

../Frenck
