### ISSUE TITLE
Zooz motion detection unavailable in 1.13.1

### ISSUE THREAD

**Issue by matt1131** [hassio-addons/addon-zwave-js-ui#519]
# Problem/Motivation

> When updating to v1.13.1, the motion detection entity in Zooz 4in1 sensors (ZSE40) becomes unavailable

## Expected behavior

> No change to entities

## Actual behavior

> Motion detection entity became unavailable. All other entities ok

## Steps to reproduce

> Update Zwave JS UI to 1.13.1

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Hi there 👋 

Add-ons wrap existing software in a way they are easy to use and install with a Home Assistant instance. In this case, it wraps Z-Wave JS UI. The issue you are reporting is with the upstream software packaged, not the add-on itself.

Please report this issue upstream with the Z-Wave JS project. Once they address the issue and release a fix for it, the add-on will be updated.

Thanks 👍 

../Frenck
