### ISSUE TITLE
Fibaro covers doesn't report state after update to 1.13.1

### ISSUE THREAD

**Issue by memphi2** [hassio-addons/addon-zwave-js-ui#520]
After updating to 1.13.1 my fibaro covers doesn't report the state.
I can see in the zwave log that the covers are sending the update, but in HA there is no change in the state.

**Comment by frenck** [comment]
Hi there @memphi2 👋 

Add-ons wrap existing software in a way they are easy to use and install with a Home Assistant instance. In this case, it wraps Z-Wave JS UI. The issue you are reporting is with the upstream software packaged, not the add-on itself.

Please report this issue upstream with the Z-Wave JS project. Once they address the issue and release a fix for it, the add-on will be updated.

Thanks 👍 

../Frenck
