### ISSUE TITLE
Multiple double tap events firing?

### ISSUE THREAD

**Issue by lkroeker** [hassio-addons/addon-zwave-js-ui#527]
# Problem/Motivation

> After a recent update, when double pressing my Jasco ZWave Dimmers the system registers four 'double presses' milliseconds apart.  These events show up identically other than the unique id.  This wouldn't be an issue, except that I use multiple double presses to trigger different actions in my system. 

## Expected behavior

> Ideally there would only be one event sent per double press. 

## Actual behavior

> Four events appear of the type: event_type: zwave_js_value_notification

## Steps to reproduce

> Bind device to double tap on the controller. Double tap light switch.

## Proposed changes

> Unknown. 
>

**Comment by frenck** [comment]
Hi there @lkroeker 👋 

It seems like you are experiencing an issue with Z-Wave JS itself, not the add-on specifically.

Add-ons wrap existing applications, in this case Z-Wave JS UI. If you experience issues with the software itself, you should report it to the upstream project. Once it gets resolved and a release with the fixes is made publicly available from upstream, the add-on will update as well.

Thanks 👍 

../Frenck
