### ISSUE TITLE
Set `host_network: true` to allow for mDNS discovery of remote Z-Wave controllers

### ISSUE THREAD

**Issue by kaechele** [hassio-addons/addon-zwave-js-ui#529]
# Problem/Motivation

[Z-Wave JS release 10.23.0](https://github.com/zwave-js/node-zwave-js/releases/tag/v10.23.0) now has the ability to discover remote Z-Wave Controllers shared through tools such as [`ser2net`](https://github.com/cminyard/ser2net) using mDNS. For mDNS to function the container needs to participate in the host network directly, as other addons with mDNS functionality do (e.g. [`hassio-addons/addon-aircast`](https://github.com/hassio-addons/addon-aircast) or [`hassio-addons/addon-airsonos`](https://github.com/hassio-addons/addon-airsonos)).

## Expected behavior

Remote Z-Wave Controllers shared through `ser2net` with mDNS enabled show up in the Z-Wave JS UI Settings for selection by the user.

![Z-Wave JS UI showing mDNS discovered device](https://github.com/hassio-addons/addon-zwave-js-ui/assets/454490/5ea6c886-fa79-4d25-af4e-2692cc7b0040)

## Actual behavior

mDNS-enabled remote Z-Wave Controllers entry as seen above is missing.

## Steps to reproduce

1. Share a Z-Wave Controller via `ser2net` using the config described here: https://github.com/zwave-js/node-zwave-js/pull/5863#issuecomment-1574037812
2. Install Z-Wave JS UI addon, if not already installed
3. Browse to the Z-Wave UI settings page and open the Z-Wave accordion. The dropdown in the "Serial Port" section will not show any mDNS-discovered Z-Wave Controllers. 

## Proposed changes

Add `host_network: true` to https://github.com/hassio-addons/addon-zwave-js-ui/blob/main/zwave-js-ui/config.yaml
I have not tested this yet and don't have the experience to assess the implications of this change, otherwise I would have sent a PR already.

**Comment by kaechele** [comment]
Just commenting to keep this issue open.

**Comment by frenck** [comment]
I don't want to put an add-on on the host network if it isn't strictly needed. In this case, it is a small enhancement for a one time setup, that brings in complications and lowers security for the full lifetime.

IMHO, that is a juice that isn't worth the squeeze.

Nevertheless, thanks for the suggestion 👍 

../Frenck
