### ISSUE TITLE
Addon installation in Homeassistant does not allow zwavejs integration to run

### ISSUE THREAD

**Issue by harryfine** [hassio-addons/addon-zwave-js-ui#538]
# Problem/Motivation

> (Why the issue was filed): Followed the 6 steps found online but with additional research, for instance the proper HA URL for the server, ws://a0d7b954-zwavejs2mqtt:3000, that was hard to find.  Got the keys from the official addon.  Disabled the zwave integration.  Installed this comminity addon.  It ran in the sidebar.  Entered my port, plus the 4 keys, legacy, access control, and the S2 authorized and unauthorized keys from the old addon.

Made sure the old addon was stopped.  Enabled the integration.  Chose ws://a0d7b954-zwavejs2mqtt:3000 as the URL, and it fails ever time.  The addon runs, I can even see devices.  I then tried removing the official addon.  It kept re-installing itself, but I edited a config file to make the pairing between the integration and official addon "false".  Again, tried to enable the integration, and received failed to connect error.

Tried rebooting, same issue. 

## Expected behavior

> (What you expected to happen): I expected the integration and the addon to run with peaceful co-existence.  But the integration will not start, meaning that my zwave homeassistant devices will not be recognized by homeassistant.

## Actual behavior

> (What actually happened):  The error message as above, integration would not start, and the zwave devices are not accessible from the homeassistant dashboard.

## Steps to reproduce

> (How can someone else make/see it happen):  I don't know, clearly it's working for some, but following the procedure precisely did not work for me.
![5](https://github.com/hassio-addons/addon-zwave-js-ui/assets/15006441/55b5b65d-611b-47fc-93d2-421706b68694)
![4](https://github.com/hassio-addons/addon-zwave-js-ui/assets/15006441/72b1dd7e-e103-4411-a856-0b6586d12401)
![1](https://github.com/hassio-addons/addon-zwave-js-ui/assets/15006441/571ec7a0-fe02-457b-983a-bbacfd8c9643)
![2](https://github.com/hassio-addons/addon-zwave-js-ui/assets/15006441/ea5e7fe5-71b5-41c5-b796-8b65f01d40bb)
![3](https://github.com/hassio-addons/addon-zwave-js-ui/assets/15006441/8fa6944f-5c08-4938-b8b6-fae25dd707c4)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by raman325** [comment]
have you enabled the websocket server in zwave-js-ui?
