### ISSUE TITLE
Locked out of Z-Wave

### ISSUE THREAD

**Issue by BertPorter** [hassio-addons/addon-zwave-js-ui#549]
## Problem

1) Z-Wave Integration error message: 
Failed to connect: Cannot connect to host localhost:3000 ssl:default [Connect call failed ('127.0.0.1',3000)].   
2) Z-Wave JS UI Addon has disappeared.

## How I got here

1) Today I installed Core Update 2023.7.3 followed by several other updates including Z-Wave JS UI. 
2) Configuration failed validation. I think it was due to a conflict with HACS Remote Home Assistant. 
3) I restored HA from the morning backup.
4)  I installed the latest HACS Remote Home Assistant before Core Update and the other updates. All seemed fine. 
5) Then I noticed the issue with Z-Wave. I realized I wasn't given the option of updating Z-Wave JS UI this time around.
6) I again restored HA from the morning backup.
7) This didn't resolve the issue with Z-Wave JS UI

## Setup

Zooz ZST10 700 controller, Minisforum PC, Proxmox. There are currently 81 installed Z-Wave devices. 

## How should I proceed?

I considered re-adding the Z-Wave JS UI Addon. I don't know the ramifications of this. Will I lose the keys from the Z-Wave settings? What would this mean? I am working on a sophisticated installation. There are many HA components that I am not versed in. I'm learning as I go.  

Thanks.

**Comment by BertPorter** [comment]
## Recommendation

Add a note to the configuration screen where Keys are entered:
"Keep a backup of these keys in a safe place in case you need to move your Z-Wave controller to another device." 
This is obvious after the fact.

## Status

1. After much searching I was able to find instructions on how to access the data in an encrypted backup. 
https://pypi.org/project/decrypt-ha-backup/
I was able to search the data in an older backup and find the Keys. This is a great tool to have in general. 

2. I currently have a running version of Home Assistant with all the latest updates including Z-Wave JS-UI  1.15.3.

## Remaining Issue

I can't Start Z-Wave JS-UI. There is a red dot in the upper right corner of the window. I get no indication/information of why it won't Start. I have tried it with the Z-Wave JS Integration both enabled and disabled.

All my Z-Wave entities are disabled on dashboards. I have another set of Z-Wave devices connected via Remote Home Assistant and they are working correctly.

All the log contains is repeated versions of this line:
`2023-08-01 03:13:53.872 INFO APP: GET /health/zwave 200 0.701 ms - 2140`

**Comment by frenck** [comment]
> Add a note to the configuration screen where Keys are entered:
> "Keep a backup of these keys in a safe place in case you need to move your Z-Wave controller to another device."
> This is obvious after the fact.

That is not a concern for the add-on. Feel free to raise such a feature request / suggestion with the Home Assistant project.

**Comment by frenck** [comment]
> All the log contains is repeated versions of this line:
> 2023-08-01 03:13:53.872 INFO APP: GET /health/zwave 200 0.701 ms - 2140

That means the add-on is running and healthy.

I've seen more cases of this, which are often solved by rebooting (powering off/on) the whole system that runs Home Assistant.

That said, this part if not in control of the add-on. Please report it with the Home Assistant Supervisor project.

../Frenck

**Comment by BertPorter** [comment]
The keys are entered on the add-on screen. That’s when this warning is relevant and when the keys can be copied. Is this screen under the purview of HA and not your team?I’m just trying to help prevent this from happening to others. On Aug 1, 2023, at 3:38 AM, Franck Nijhof ***@***.***> wrote:﻿

Add a note to the configuration screen where Keys are entered:
"Keep a backup of these keys in a safe place in case you need to move your Z-Wave controller to another device."
This is obvious after the fact.

That is not a concern for the add-on. Feel free to raise such a feature request / suggestion with the Home Assistant project.

**Comment by BertPorter** [comment]
Thanks for your quick response. I will try your suggestions on the hardware tomorrow.On Aug 1, 2023, at 3:39 AM, Franck Nijhof ***@***.***> wrote:﻿

All the log contains is repeated versions of this line:
2023-08-01 03:13:53.872 INFO APP: GET /health/zwave 200 0.701 ms - 2140

That means the add-on is running and healthy.
I've seen more cases of this, which are often solved by rebooting (powering off/on) the whole system that runs Home Assistant.
That said, this part if not in control of the add-on. Please report it with the Home Assistant Supervisor project.
../Frenck
