### ISSUE TITLE
Would not connect to integration after 1.15.4 update

### ISSUE THREAD

**Issue by lishan89uc** [hassio-addons/addon-zwave-js-ui#556]
# Problem/Motivation

>: After upgrading from 1.15.3 to 1.15.4 the zwavejs integration in home assistant would not connect to the  zwave js ui 

## Expected behavior

> The integration to connect automatically or connect after the integration is reloaded.

## Actual behavior

> got this error: `Config entry 'Z-Wave JS' for zwave_js integration not ready yet: Failed to connect: Cannot connect to host a0d7b954-zwavejs2mqtt:3000 ssl:default [Connect call failed ('172.30.33.2', 3000)]; Retrying in background`

## Steps to reproduce

> All I did was install 1.15.4 
   Rolling back to 1.15.3 seem to have solved the issue

## Proposed changes

none

**Comment by frenck** [comment]
Duplicate of #553
