### ISSUE TITLE
Compact view sort

### ISSUE THREAD

**Issue by GitHubGoody** [hassio-addons/addon-zwave-js-ui#560]
I like the new compact view, but would appreciate the ability to sort the tiles more than the default (Node ID). If it helps (cannot be added all at once), this is the order I would prefer options to be added:

1. Name
2. Location
3. Last Active
4. Status
5. Power
6. etc.

**Comment by frenck** [comment]
I think you are in the wrong place. This is the repository that provides the add-on and its development, not Z-Wave JS UI itself. Add-on wrap existing applications. Please redirect your suggestion to the Z-Wave JS UI project.

../Frenck
