### ISSUE TITLE
Issue with turn on or off a lot off devices at the "same" time

### ISSUE THREAD

**Issue by hjallex** [hassio-addons/addon-zwave-js-ui#561]
# Problem/Motivation
Some z-wave devices will not turn on or off when sending signal to more than one devices att the same time. 
From Schedule automations. (When sun sets - turn on this devices). After a couple seconds some devices will go offline.
To kep dem to stay online or active in UI or automations I need to ping every device one time.

> (Why the issue was filed)
The Z-wave network need to be more stable.

## Expected behavior
When sending on or off to more than one device in an automation schedule it shuld be on or off directley.

> (What you expected to happen)
Turn the devices on or off without issue?
If it is a connection issue with some device it will tell me in the log?

## Actual behavior
The device went inaccessible.

> (What actually happened)
The device went offline from the UI. Somtimes the switch was set and then turnd offline.

## Steps to reproduce

> (How can someone else make/see it happen)
Maybe try my hardware and my automation code.

## Proposed changes
Give me an error and tell me what is wrong in the log.
Turn it on or off and give at least 1sec to turn on or off if it is a lot of units.

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

I have been using a Telldus live V2 to this devices for a couple years. 
With the Telldus is was no issue...
The units I'm using right now is:
RPI 4 64bit 4GB Ram
Aeotec Z-stick 7 ( ZWA010-C) (FW: V7.19.2) (SDK v7.19.2)
Fibaro FGS223
Fibaro FGD212
Fibaro FGWP102
Qubino ZMNHOD
Telldus TZWP-100

Code:
`description: Ny test av tänd belysning när solen går NER
trigger:
  - platform: sun
    event: sunset
    offset: 0
condition: []
action:
  - parallel:
      - type: turn_off
![Skärmklipp HA Parallel](https://github.com/hassio-addons/addon-zwave-js-ui/assets/74986552/9853f22e-8177-4f36-bae0-095ab55e05da)

        device_id: 3ee332c621f88be9fc774b1e7f6f4508
        entity_id: 20b676935250220185b64c33a57404d8
        domain: switch
      - type: turn_on
        device_id: 043072cf243499613981ad80bf3c95b6
        entity_id: switch.stolpe
        domain: switch
      - type: turn_on
        device_id: 3ee332c621f88be9fc774b1e7f6f4508
        entity_id: switch.kok_fonster_kokslampa_2
        domain: switch
      - type: turn_on
        device_id: e36ec7dd3c1d80405c530329b8cb9764
        entity_id: switch.utebel_dorr_fasad
        domain: switch
      - type: turn_on
        device_id: 890b10b646d29393066f72401ae6c682
        entity_id: switch.spottar_badtunna_2
        domain: switch
      - type: turn_on
        device_id: 2a48900aa6ebd799a989595da54dbdf8
        entity_id: switch.fonsterspott
        domain: switch
      - type: turn_on
        device_id: 80f6d1a333eb7863435beb5b93afb943
        entity_id: switch.spottar_fonster_q2
        domain: switch
      - type: turn_on
        device_id: f0e75ea104bff56cdd87fca94aa6d451
        entity_id: switch.spottar_fonstermsyg
        domain: switch
      - type: turn_on
        device_id: 156aa81ebfc6a7be087f9256671abbc7
        entity_id: light.tvattstuga_utelampan
        domain: light
        brightness_pct: 100
      - type: turn_on
        device_id: 8b53cfb541a80471af6e010b1011e644
        entity_id: switch.fonster_forrad
        domain: switch
      - type: turn_on
        device_id: a50cdb833212a52f273fdf9092dc46e0
        entity_id: switch.fonster_tvrum
        domain: switch
      - type: turn_on
        device_id: d04d0e5adf4487aebcb64ca912f50b0d
        entity_id: switch.fonster_vardagsrum
        domain: switch
      - type: turn_on
        device_id: 013b33b4eb5be91c4607e05ca7754fb9
        entity_id: switch.fonster_sovrum
        domain: switch
      - type: turn_on
        device_id: e6ab50ab67816200a3523584d52acbe2
        entity_id: switch.byra_lampa
        domain: switch
      - type: turn_on
        device_id: ae6b7cdebd5a8649026dfa8d382163b2
        entity_id: light.spottar_fonster_2
        domain: light
        brightness_pct: 25
      - type: turn_on
        device_id: 8c11dc35076fa656fa3216b27746435e
        entity_id: light.vitrinskap
        domain: light
        brightness_pct: 35
      - type: turn_on
        device_id: 7beb9deca8553ee053e09e43f0d78a39
        entity_id: switch.fonstersmyg_spottar_vu_ute
        domain: switch
      - type: turn_on
        device_id: 38edf3fa5b8d862d3b3a56e8bb626179
        entity_id: switch.tvattstuga_fonster_2
        domain: switch
mode: single
`

**Comment by stefanes** [comment]
Unrelated to the issue, but you could try to use multicast instead of turning the lights on/off one by one: https://github.com/stefanes/home-assistant-config/blob/main/packages/z-wave-multicast.yaml

**Comment by hjallex** [comment]
Hi,

Maybe I can give it a try later on.
Since a few newer updates back, it works as it should. 🙂
