### ISSUE TITLE
with v1.15.7 multilevel sensor data from HEATIT thermostat not anymore reported

### ISSUE THREAD

**Issue by Lateadapter** [hassio-addons/addon-zwave-js-ui#565]
# Problem/Motivation
I'm using HEATIT Z-TRM3 Floor-Heating-Thermostat.
After upgrade from v1.15.6 to v.1.15.7 reporting of multilevel sensors v5 (air temperature) disappeared.
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce
The issue was only realized by looking into the graph of historical sensor data - no changed values since upgrade.
Everything else seems to work.
By restoring previous version v1.15.6 the issue was solved immediately.
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by magne74** [comment]
I have the same issue with a Heatit z-relay.

**Comment by foreign-sub** [comment]
same here

**Comment by christofferhohi** [comment]
Same problem here with all 5 Heatit thermostats after updating from 1.15.5 to 1.15.8

**Comment by henrikhermansen** [comment]
I have opened zwave-js/zwave-js-ui#3256 to hopefully speed up the process of patching this.

**Comment by frankis78** [comment]
I have same problem. It removes the multilevel sensor, and therefor we cannot get air temperature anymore.
Device sends the temperature, but in log i can see that it disregards it.

**Comment by henrikhermansen** [comment]
A fix in zwave-js-ui has now been released with version 8.24.1.
It seems the bot is kinda fast at updating this, but the releases of this addon seems to come a bit less regularly. Can you please ensure this addon gets patched as soon as zwave-js-ui is updated to most recent version, @frenck ?

**Comment by frenck** [comment]
I am not available, as I am enjoying a holiday with my family abroad right now.

**Comment by henrikhermansen** [comment]
Issue is fixed now with release of 1.15.9 🎉

**Comment by Lateadapter** [comment]
Fix confirmed. Thanks to anyone involved!

**Comment by magne74** [comment]
I don't get a 1.15.9 update in HA. Addon...
