### ISSUE TITLE
Outbound communication dead after a few hours, and I'm not alone

### ISSUE THREAD

**Issue by lovekull76** [hassio-addons/addon-zwave-js-ui#572]
# Problem/Motivation

After a while (1-2h) HASS can't control devices. Inbound OK, not outbound. Lokal control is reflected i HA.
Reload of add-on fix it temporarily.

## Expected behavior

HASS able to control z-wave devices.

## Actual behavior

Devices is not reacting to sent command.

## Steps to reproduce

Upgrade to 1.15.9

## Proposed changes

There is a discussion about the issue here:
https://github.com/home-assistant/core/issues/99736

**Comment by sinclairpaul** [comment]
As per the discussion there, it really needs to be discussed at https://github.com/zwave-js/node-zwave-js 

The addon wraps that and will be updated with whatever fixes are implemented,

**Comment by lovekull76** [comment]
> The addon wraps that and will be updated with whatever fixes are implemented

Great, looks like there is a fix for it now: https://github.com/zwave-js/node-zwave-js/releases/tag/v11.14.2
