### ISSUE TITLE
U-Tec UBolt Pro ZWave Locks not updating their status correctly 

### ISSUE THREAD

**Issue by billasw1** [hassio-addons/addon-zwave-js-ui#577]
# Problem/Motivation

> Locks showing unlocked / locked status after locking / unlocking from dashboard and vice versa

## Expected behavior

> Lock should unlock or lock when dashboard button pressed or triggered from automation

## Actual behavior

> Intermittently the locks will change status but the actual lock will not change state

## Steps to reproduce

> it’s intermittent but only started after upgrading the ZWave FW to 1.53 and won’t let me downgrade 

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by demonavai** [comment]
I have a similar issue in SmartThings. Yale YRD110-ZW-US. The hub will report (and continue reporting) an "unlocked" condition exactly 1 hour after auto-lock or a manual locking.  I'm curious if your "intermittent" issue is actually 1 hour after any changes at the device. Two different manufacturers running on two different hubs having a similar issue (1 hour delay) could point to a Z-Wave issue.
