### ISSUE TITLE
No Image Available for 2.2.1

### ISSUE THREAD

**Issue by dutchboy92** [hassio-addons/addon-zwave-js-ui#600]
# Problem/Motivation

> The add-on does not start after upgrading to 2.2.1

## Expected behavior

> Supervisor downloading the updated image.

## Actual behavior

> Supervisor is unable to find the image to download.
> 
> 23-10-19 08:27:49 ERROR (SyncWorker_3) [supervisor.docker.manager] Image ghcr.io/hassio-addons/zwave-js-ui/aarch64:2.2.1 does not exist for addon_a0d7b954_zwavejs2mqtt

## Steps to reproduce

> Upgrade from 2.2.0 to 2.2.1

**Comment by frenck** [comment]
It does exists:

https://ghcr.io/hassio-addons/zwave-js-ui/aarch64:2.2.1


![CleanShot 2023-10-20 at 08 44 34@2x](https://github.com/hassio-addons/addon-zwave-js-ui/assets/195327/bd5451e3-dba1-4f16-af0b-002f8dc6b8a3)

And has been downloaded quite a lot. Seems like you have a different issue/network issue.

../Frenck
