### ISSUE TITLE
Dark Mode doesn't persist

### ISSUE THREAD

**Issue by jprasm** [hassio-addons/addon-zwave-js-ui#609]
# Problem/Motivation

> I prefer dark mode, and I cannot lie?

## When changing the UI to dark mode, one would expect it to stay like that when returning to the UI

> Previous versions of this addon worked perfectly when choosing dark mode

You turn on dark mode with the little toggle, and dark mode is enabled. You leave to go somewhere else within home assistant and return to find that dark mode is no longer active.

> (What actually happened)

## Toggling back and forth

> Turn on dark mode, leave then come back. Tell me if I'm the only one who has this problem and I'll be quiet :) 

## Make dark mode great again

> I wish I knew what to recommend.

**Comment by MuppetOwl** [comment]
Can confirm same issue

**Comment by sinclairpaul** [comment]
Upstream issue https://github.com/zwave-js/zwave-js-ui/pull/3390 that would be fixed in the latest release.  If not please log upstream.
