### ISSUE TITLE
Fix problems with alpine on arm

### ISSUE THREAD

**Issue by robertsLando** [hassio-addons/addon-zwave-js-ui#626]
Hi @frenck, I would like to suggest you a possible way to fix the problem related to releases.

What about using my [docker container](https://hub.docker.com/r/zwavejs/zwave-js-ui/tags) as base and copy files from there instead of cloning and compiling everythin? You could simply use the arg `ARG ZWAVE_JS_UI_VERSION="9.6.0"` to do something like:

```
FROM zwavejs/zwave-js-ui:9.6.0
```

**Comment by frenck** [comment]
Sorry I won't be using other bases. This is not just a problem for this addon.

**Comment by robertsLando** [comment]
Maybe I explained wrongly, you can still use your base but use mine as a build step from where just copy the already builded sources

**Comment by robertsLando** [comment]
I have submitted a PR to show you what I mean
