### ISSUE TITLE
Z-Wave JS UI frequently off-line

### ISSUE THREAD

**Issue by papabak** [hassio-addons/addon-zwave-js-ui#636]
I have HA running on a RPi 3. I have Z-Wave JS UI running using a Aeotec Z-Stick 7 on a usb extention cable. I have only one Z-wave device (Heatit Z-TRM3 thermostat).
Most of the time the add-on is active, but frequently it become inactive. I then try to restart the Z-wave JS UI add-on which often fails. I have to restart HA completely.

**Comment by frenck** [comment]
There is not much in this issue description that helps with triaging an issue.

Please provide things like logs details, reproduction steps and things like that.

../Frenck

**Comment by frenck** [comment]
Closing, as there was no response.

**Comment by papabak** [comment]
I apologize Frenck. My HA had become a mess. Got myself a new Odroid N2+ and started all over Z-wave JS UI is working flawless.
________________________________
Van: Franck Nijhof ***@***.***>
Verzonden: Friday, February 2, 2024 11:42:17 AM
Aan: hassio-addons/addon-zwave-js-ui ***@***.***>
CC: papabak ***@***.***>; Author ***@***.***>
Onderwerp: Re: [hassio-addons/addon-zwave-js-ui] Z-Wave JS UI frequently off-line (Issue #636)


Closed #636<https://github.com/hassio-addons/addon-zwave-js-ui/issues/636> as not planned.
