### ISSUE TITLE
Problems with TKB wall switch TZ55S since v3.7.0

### ISSUE THREAD

**Issue by PatrBal** [hassio-addons/addon-zwave-js-ui#681]
# Problem/Motivation

After updating to v3.7.0 (or any later version) I can't change the state of my TKB wall switch TZ55S from home assistant.
All other zwave devices work fine.

## Expected behavior

Be able to change the state of the device from home assistant as I used to.

## Actual behavior

The command is correctly pusblished on MQTT and appears in the logs of zave-js-ui. But immediately after, the opposite command is pusblished on MQTT and appears in the logs of zave-js-ui. And the device remains as before without changing state.

When reverting to v3.6.0, all works fine. Upgrading to any later version breaks the control of the TKB wall switch TZ55S from Home Assistant.
I have spent hours to look for a solution without finding anything. I am stuck with v3.6.0. I would very grateful if anybody can point towards a hint to troubleshoot. Thanks in advance.

**Comment by jag100UK** [comment]
I have the same problem with my TKB TZ67 Dimmers.

Home Assistant is receiving status updates when I manually turn the device on and off by pushing the button, but I can't control it from HA.

Debug has the following messages but no errors
 
```
2024-07-31 12:53:31.415 INFO Z-WAVE: [Node 091] Value updated: 38-0-targetValue 0 => 255
2024-07-31 12:53:36.789 INFO Z-WAVE: [Node 091] Value updated: 38-0-currentValue 0 => 0
```

I would downgrade back to 3.6 but then the add-on won't start as 2024.7.3 reports the addon is out of date.

**Comment by PatrBal** [comment]
The problem is still there on 3.10. I had to revert to 3.6 and can no longer update Home Assistant?
