### ISSUE TITLE
Devices unavailable and then removed automatically after update to 9.14.6

### ISSUE THREAD

**Issue by Fjury** [hassio-addons/addon-zwave-js-ui#686]
After Upgrade to HoleAssitant Addon 3.8.6 based on v9.14.6 I see some Devices where excluded from network while switching the state.

Direct after upgrade all devices seems to work.
But I have two [Water Valves](https://devices.zwave-js.io/?jumpTo=0x0152:0x0003:0x0512:0.0)
The first disconnects from my Z-Wave network after I toggle the switch in HomeAssiatant from off to on.
After its state was unavailable I disconnect it for a reboot. That’s not help to connect again.
After that I reboot HomeAssiatant, what totally removed this device from Z-Wave JS Ui.

At this point the second valve was still available and connected. But after I try to switch this to state on, the same procedure starts and the valve is now also in disconnected state.

Because ZWaveJS Logs are disabled I think I cannot provide something useful :-(

If you need some more details/logs before I reboot HA again and the second disconnected device is also removed from my network, please let me know.

**Comment by AlbertShovelton** [comment]
I seem to be having similar behavior all my z-wave devices, zoos light switches and smart door locks. The devices seem to drop randomly, and I can get them back on the network by reinterviewing, or removing and reading. 

The behavior started when I migrated HA from a RPi to a VM, which coincides with the release of 3.8.6
