### ISSUE TITLE
Thermometers not giving proper values cafter update 3.9.0

### ISSUE THREAD

**Issue by ArLo69** [hassio-addons/addon-zwave-js-ui#688]
# Problem/Motivation

Right after updating to 3.9.0 all thermometers stopped working.

## Expected behavior

Thermometers displaying the actual air temperature values

Everspring devices show a temperature which is about 28 C lower then the actual value which is in the devices display. But these are showing new values through time after the update.
Aeotec and Secure Meters thermometers are since the update only showing the value which it had right before the update. A graph is a flat line ever since. Even with forced reports and tampering the temperature.
Soft reset, unplugging the 700 series hub and restarting HA all did not solve the issue.
All other devices work and respond properly. Thermometers do report in at interval or forced on the device.

> (What actually happened)

Update to 3.9.0
Monitor the air temperature values on a graph for example to see the behaviour.

## Proposed changes

Correct the air temperature readings to make them work as up until 3.8.6

**Comment by Friedi1970** [comment]
I am facing the same issue on two of my sensors. They are displaying -3°C while ist actually about 25°C in the real world.

**Comment by frenck** [comment]
This a driver issue, which should be reported with the Z-Wave JS project instead.

../Frenck
