### ISSUE TITLE
Priority route not visible with "star"

### ISSUE THREAD

**Issue by Beer17HWAM** [hassio-addons/addon-zwave-js-ui#692]
Priority routes not visible with "star" in the network graph. Docker version has no problem but HAOSS version isn't displaying stars. My friend @jeroen84s has this problem. 

See https://github.com/zwave-js/zwave-js-ui/issues/3492

With the latest HAOSS zwave still NO STARS.

**Comment by frenck** [comment]
This add-on does nothing with routing, all other assets work.

https://github.com/hassio-addons/addon-zwave-js-ui/blob/4c2d7c534836beeb3d80612d214e5014948dd582/zwave-js-ui/rootfs/etc/nginx/templates/ingress.gtpl#L6

We pass in our path; if there is an assets that isn't honoring that, it would be an upstream issue, not an add-on issue.

../Frenck

**Comment by TheDK** [comment]
> This add-on does nothing with routing, all other assets work.
> 
> https://github.com/hassio-addons/addon-zwave-js-ui/blob/4c2d7c534836beeb3d80612d214e5014948dd582/zwave-js-ui/rootfs/etc/nginx/templates/ingress.gtpl#L6
> 
> We pass in our path; if there is an assets that isn't honoring that, it would be an upstream issue, not an add-on issue.
> 
> ../Frenck

OT is referring to the preferred route in the Z-Wave network (displaying this is a feature of the add-on), but that still should not be an issue with packaging the add-on.

**Comment by frenck** [comment]
> The file is simply not available!!

Correct, as the path is not right. The `X-External-Path` isn't honored by upstream.
That is not an add-on issue.

../Frenck

**Comment by Beer17HWAM** [comment]
I give it up. My separate zwave docker is working fine. I see stars. My friend doesn't have stars in his HA zwave addon. If the developers of zwave and the HA addon are not able to fix it I give up.

**Comment by Beer17HWAM** [comment]
Works! Thanks you all!!!
![image](https://github.com/user-attachments/assets/127d7d2a-53db-44d6-9778-9e71023dad71)
