### ISSUE TITLE
Error on update 

### ISSUE THREAD

**Issue by MiAutomations** [hassio-addons/addon-zwave-js-ui#713]
# Problem/Motivation

![image](https://github.com/user-attachments/assets/0ce8bd7a-be6e-4ae5-847d-4082cb38f83e)

Hello I'm facing a issue when I try to update the addon for the last available version 

![image](https://github.com/user-attachments/assets/afc84cb7-cd75-4e9a-a7c1-eb1da412b5ea)

Can you please help me in order to try solve this issue? Thank you

**Comment by frenck** [comment]
the error shows a timeout, meaning you have either network or other connection issues; or have problem reaching the GitHub container registry.

This is not an add-on issue.

../Frenck
